language: python
sudo: required

python: 3.6

services:
  - docker

branches:
  only:
    - master

install:
  - pip install daiquiri requests

script:
  - ./travis_run.py

env:
  global:
    - DOCKER_USERNAME=greengloves
    - secure: MQrcZlbcOVi9gHQepO1R4r0bHBRWnomK9uhyXjFVMJZ1C8FO1AU5zD/yzlfdleR86cy5P5YWcjPZlZRIXQS+qnLOJs259uWpGqRvWp7wpiTFCztZgL9E1NjIsNuAEmA+q0N8gU/L4HkvS32W5X/FemVyInl+WCojeYDozK5j0wXymoTRjybcx+MOLoKbJQfEtsYErQBw8GgpOVRAnxwdgq6gN7KzJGNGvll6vjzoAt17UD4JTcpoWrpKIj9/gtuPmM4zH2q900YoE4tu0gfXTRnXeMk82cYgJO09iOr1CiXsK5BmZJOMnzgkipDRCs88kk6zcpG3WLT1S7Y/kebuRJXR/LLni49ZZXZZVreP1tKoaFiE+3yB3WqRWdMVNMui5k+ORIca2K10HyBU4qP3r30z8HgsPlypcx/haPwf8K4LwvT6IDpZW2iuaN9V8ktQ/IrWjecpy2TvpyuieE5mP91BEWk+byjsdTZTVJpE2mLprFUTOIfReC//BIqSbrCucUByTbnMPCBP2A9SBMpuZyr2ru9SxxSv59kpwm8AOyu8Mzw1bIuUWPtIZBXYSX3W7F0jZkMAFJ1n/ugB+46Uxz1ClFhGcnhHIRHJ4LPgqbP5kLr9WpTfcQQ1Wf3J3ksXM+3toXafFuxI+5ldn/VNiX8pTJ1EmlpQxLY9t2hIfMY=
